# Generated by Django 5.0.7 on 2024-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('writer', models.CharField(max_length=30)),
                ('body', models.TextField()),
                ('created_time', models.DateField(auto_now_add=True)),
                ('edit_time', models.DateField(auto_now=True)),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
